name: Weekly Obfuscated Builds for .NET Framework 4.8.1

on:
  schedule:
    - cron: '0 0 * * 1' # Runs every Monday at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-obfuscate:
    runs-on: windows-latest # .NET Framework 4.8.1 is pre-installed
    steps:
      # Step 1: Checkout the automation repo
      - name: Checkout automation repository
        uses: actions/checkout@v4

      # Step 2: Clone tool repositories
      - name: Clone repositories
        run: |
          git clone https://github.com/BloodHoundAD/SharpHound.git
          git clone https://github.com/GhostPack/Seatbelt.git
          git clone https://github.com/GhostPack/Rubeus.git
          git clone https://github.com/GhostPack/Certify.git
          git clone https://github.com/Mayyhem/SharpSCCM.git
        shell: pwsh

      # Step 3: Update .csproj files for .NET Framework 4.8.1 (handle both SDK and legacy styles)
      - name: Update project files
        run: |
          $tools = @("SharpHound", "Seatbelt", "Rubeus", "Certify", "SharpSCCM")
          foreach ($tool in $tools) {
            $csprojFiles = Get-ChildItem -Path ./$tool -Recurse -Include *.csproj
            foreach ($csproj in $csprojFiles) {
              $content = Get-Content $csproj.FullName
              
              # For SDK-style: Replace <TargetFramework>
              $content = $content -replace '<TargetFramework>.*</TargetFramework>', '<TargetFramework>net481</TargetFramework>'
              
              # For legacy-style: Replace or add <TargetFrameworkVersion>
              if ($content -match '<TargetFrameworkVersion>.*</TargetFrameworkVersion>') {
                $content = $content -replace '<TargetFrameworkVersion>.*</TargetFrameworkVersion>', '<TargetFrameworkVersion>v4.8.1</TargetFrameworkVersion>'
              } else {
                # Add if missing (insert after first <PropertyGroup>)
                $propGroupIndex = $content.IndexOf('<PropertyGroup>') + 1
                if ($propGroupIndex -gt 0) {
                  $content = $content[0..($propGroupIndex-1)] + '<TargetFrameworkVersion>v4.8.1</TargetFrameworkVersion>' + $content[$propGroupIndex..$content.Length]
                }
              }
              
              Set-Content $csproj.FullName $content
            }
          }
        shell: pwsh

      # Step 4: Build tools with MSBuild
      - name: Build tools
        run: |
          $tools = @("SharpHound", "Seatbelt", "Rubeus", "Certify", "SharpSCCM")
          foreach ($tool in $tools) {
            $sln = Get-ChildItem -Path ./$tool -Recurse -Include *.sln | Select-Object -First 1
            if ($sln) {
              & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" $sln /p:Configuration=Release /p:Platform="Any CPU"
            } else {
              $csproj = Get-ChildItem -Path ./$tool -Recurse -Include *.csproj | Select-Object -First 1
              & "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\MSBuild.exe" $csproj /p:Configuration=Release /p:Platform="Any CPU"
            }
          }
        shell: pwsh

      # Step 5: Download and setup ConfuserEx
      - name: Setup ConfuserEx
        run: |
          Invoke-WebRequest -Uri "https://github.com/mkaring/ConfuserEx/releases/download/v1.6.0/ConfuserEx-CLI.zip" -OutFile "ConfuserEx.zip"
          Expand-Archive -Path ConfuserEx.zip -DestinationPath ./ConfuserEx
        shell: pwsh

      # Step 6: Obfuscate binaries (flexible path for SDK/legacy outputs)
      - name: Obfuscate with ConfuserEx
        run: |
          $tools = @("SharpHound", "Seatbelt", "Rubeus", "Certify", "SharpSCCM")
          foreach ($tool in $tools) {
            $exe = Get-ChildItem -Path ./$tool -Recurse -Include "$tool.exe" | Where-Object { $_.FullName -like "*bin\Release*" } | Select-Object -First 1
            if ($exe) {
              $crproj = Join-Path .\.github\config "$tool.crproj"
              (Get-Content .\.github\config\template.crproj) -replace '{{EXE_PATH}}', $exe.FullName -replace '{{OUTPUT_DIR}}', "$tool\output-obfuscated" | Set-Content $crproj
              & ./ConfuserEx/Confuser.CLI.exe -n $crproj
            }
          }
        shell: pwsh

      # Step 7: Package and store artifacts
      - name: Package artifacts
        run: |
          $date = Get-Date -Format "yyyy-MM-dd"
          $tools = @("SharpHound", "Seatbelt", "Rubeus", "Certify", "SharpSCCM")
          foreach ($tool in $tools) {
            if (Test-Path ./$tool/output-obfuscated) {
              Compress-Archive -Path ./$tool/output-obfuscated/* -DestinationPath ./$tool-$date.zip
            }
          }
        shell: pwsh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: obfuscated-binaries-net481
          path: |
            *.zip
          retention-days: 7