name: Obfuscate SharpSCCM with Codecepticon

on:
  push:
    branches: [ main ]

jobs:
  obfuscate:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: main-repo

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'  # Codecepticon and SharpSCCM typically use .NET 6

    - name: Install NuGet
      run: |
        curl -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
        mkdir -p D:\a\tools\nuget
        mv nuget.exe D:\a\tools\nuget\nuget.exe
      shell: powershell

    - name: Clone SharpSCCM
      run: |
        git clone https://github.com/Mayyhem/SharpSCCM.git
        cd SharpSCCM
        D:\a\tools\nuget\nuget.exe restore SharpSCCM.sln -Source "https://api.nuget.org/v3/index.json"
      shell: powershell

    - name: Build SharpSCCM
      run: |
        cd SharpSCCM
        dotnet build SharpSCCM.sln --configuration Release --no-restore
      shell: powershell

    - name: Clone Codecepticon
      run: |
        git clone https://github.com/sadreck/Codecepticon.git
      shell: powershell

    - name: Restore Codecepticon with Pinned Roslyn
      run: |
        cd Codecepticon
        dotnet add Codecepticon package Microsoft.CodeAnalysis.CSharp.Workspaces --version 3.9.0
        dotnet add Codecepticon package Microsoft.CodeAnalysis.Workspaces.MSBuild --version 3.9.0
        dotnet restore
      shell: powershell

    - name: Build Codecepticon
      run: |
        cd Codecepticon
        dotnet build --configuration Release --no-restore --output Release/net6.0
      shell: powershell

    - name: Debug Directory Structure
      run: |
        cd Codecepticon
        dir
        cd Release
        dir
        cd net6.0
        dir
      shell: powershell
      continue-on-error: true  # Continue even if net6.0 is missing to see output

    - name: Obfuscate SharpSCCM
      run: |
        cd Codecepticon/Release/net6.0
        ./Codecepticon.exe --action obfuscate --module csharp --solution ../../SharpSCCM/SharpSCCM.sln --verbose --rename-strategy random --encrypt-strings --output-mappings ../../obfuscated-mappings.html
      shell: powershell

    - name: Build Obfuscated SharpSCCM
      run: |
        cd SharpSCCM
        D:\a\tools\nuget\nuget.exe restore SharpSCCM.sln -Source "https://api.nuget.org/v3/index.json"
        dotnet build SharpSCCM.sln --configuration Release --no-restore
      shell: powershell

    - name: Upload Obfuscated Binary
      uses: actions/upload-artifact@v4
      with:
        name: obfuscated-sharpsccm
        path: SharpSCCM/bin/Release/net6.0/SharpSCCM.exe
        retention-days: 7

    - name: Upload Mappings
      uses: actions/upload-artifact@v4
      with:
        name: obfuscation-mappings
        path: obfuscated-mappings.html