name: Obfuscate SharpSCCM with Codecepticon

on:
  push:
    branches: [ main ]

jobs:
  obfuscate:
    runs-on: windows-latest  # Use Windows for .NET compatibility; Linux possible with tweaks

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: main-repo  # Shallow clone of your repo (if hosting this workflow)

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'  # Adjust to match SharpSCCM/Codecepticon needs

    - name: Clone and build SharpSCCM
      run: |
        git clone https://github.com/Mayyhem/SharpSCCM.git
        cd SharpSCCM
        dotnet restore SharpSCCM.sln  # Ensure it builds cleanly before obfuscation
        dotnet build SharpSCCM.sln --configuration Release --no-restore
        cd ..

    - name: Clone and build Codecepticon
      run: |
        git clone https://github.com/sadreck/Codecepticon.git
        cd Codecepticon
        # Restore with pinned Roslyn v3.9.0 (add to Directory.Build.props if needed)
        dotnet restore
        dotnet build --configuration Release --no-restore
        cd ..

    - name: Obfuscate SharpSCCM
      run: |
        cd Codecepticon/Release/net6.0  # Or net8.0 depending on build
        # Example CLI: Adjust params via generator; use XML for complex configs
        ./Codecepticon.exe --action obfuscate --module csharp --solution ../path/to/SharpSCCM/SharpSCCM.sln --verbose --rename-strategy random --encrypt-strings --output-mappings ../obfuscated-mappings.html
        # If using XML: ./Codecepticon.exe --config path/to/config.xml
      shell: pwsh  # PowerShell for Windows compatibility

    - name: Build obfuscated SharpSCCM
      run: |
        cd SharpSCCM
        dotnet build SharpSCCM.sln --configuration Release --no-restore
        # Output: bin/Release/netX.0/SharpSCCM.exe (now obfuscated)

    - name: Upload obfuscated binary
      uses: actions/upload-artifact@v4
      with:
        name: obfuscated-sharpsccm
        path: SharpSCCM/bin/Release/net*/SharpSCCM.exe
        retention-days: 7

    - name: Upload mappings (for CLI rewriting)
      uses: actions/upload-artifact@v4
      with:
        name: obfuscation-mappings
        path: Codecepticon/obfuscated-mappings.html