name: Obfuscate SharpSCCM with Codecepticon

on:
  push:
    branches: [ main ]

jobs:
  obfuscate:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        path: main-repo

    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '6.0.x'  # SharpSCCM uses .NET 6; adjust if needed

    - name: Install NuGet
      run: |
        curl -o nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
        mkdir -p D:\a\tools\nuget
        mv nuget.exe D:\a\tools\nuget\nuget.exe
      shell: powershell

    - name: Clone SharpSCCM
      run: |
        git clone https://github.com/Mayyhem/SharpSCCM.git
        cd SharpSCCM
        # Restore NuGet packages explicitly for packages.config
        D:\a\tools\nuget\nuget.exe restore SharpSCCM.sln -Source "https://api.nuget.org/v3/index.json"
      shell: powershell

    - name: Build SharpSCCM
      run: |
        cd SharpSCCM
        dotnet build SharpSCCM.sln --configuration Release --no-restore
      shell: powershell

    - name: Clone and build Codecepticon
      run: |
        git clone https://github.com/sadreck/Codecepticon.git
        cd Codecepticon
        # Pin Roslyn packages to 3.9.0
        dotnet add Codecepticon package Microsoft.CodeAnalysis.CSharp.Workspaces --version 3.9.0
        dotnet add Codecepticon package Microsoft.CodeAnalysis.Workspaces.MSBuild --version 3.9.0
        dotnet restore
        dotnet build --configuration Release --no-restore
      shell: powershell

    - name: Obfuscate SharpSCCM
      run: |
        cd Codecepticon/Release/net6.0
        # Basic obfuscation; adjust params via CommandLineGenerator.html
        ./Codecepticon.exe --action obfuscate --module csharp --solution ../../SharpSCCM/SharpSCCM.sln --verbose --rename-strategy random --encrypt-strings --output-mappings ../../obfuscated-mappings.html
      shell: powershell

    - name: Build obfuscated SharpSCCM
      run: |
        cd SharpSCCM
        D:\a\tools\nuget\nuget.exe restore SharpSCCM.sln -Source "https://api.nuget.org/v3/index.json"
        dotnet build SharpSCCM.sln --configuration Release --no-restore
      shell: powershell

    - name: Upload obfuscated binary
      uses: actions/upload-artifact@v4
      with:
        name: obfuscated-sharpsccm
        path: SharpSCCM/bin/Release/net6.0/SharpSCCM.exe
        retention-days: 7

    - name: Upload mappings
      uses: actions/upload-artifact@v4
      with:
        name: obfuscation-mappings
        path: obfuscated-mappings.html