name: Weekly Obfuscated Builds for .NET Framework 4.8.1

on:
  schedule:
    - cron: '0 0 * * 1' # Runs every Monday at midnight UTC
  workflow_dispatch: # Allows manual triggering

jobs:
  build-and-obfuscate:
    runs-on: windows-latest # .NET Framework 4.8.1 is pre-installed
    steps:
      # Step 1: Checkout the automation repo
      - name: Checkout automation repository
        uses: actions/checkout@v4

      # Step 2: Clone tool repositories
      - name: Clone repositories
        run: |
          git clone https://github.com/BloodHoundAD/SharpHound.git
          git clone https://github.com/GhostPack/Seatbelt.git
          git clone https://github.com/GhostPack/Rubeus.git
          git clone https://github.com/GhostPack/Certify.git
          git clone https://github.com/Mayyhem/SharpSCCM.git
        shell: pwsh

      # Step 3: Install NuGet to restore dependencies
      - name: Install NuGet
        run: |
          Invoke-WebRequest -Uri "https://dist.nuget.org/win-x86-commandline/latest/nuget.exe" -OutFile "nuget.exe"
        shell: pwsh

      # Step 4: Add MSBuild to PATH (using official action based on vswhere)
      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v2
        with:
          msbuild-architecture: x64  # Use x64 for better compatibility with .NET Framework builds

      # Step 5: Update .csproj files for .NET Framework 4.8.1 (handle both SDK and legacy styles)
      - name: Update project files
        run: |
          $tools = @("SharpHound", "Seatbelt", "Rubeus", "Certify", "SharpSCCM")
          foreach ($tool in $tools) {
            $csprojFiles = Get-ChildItem -Path ./$tool -Recurse -Include *.csproj
            foreach ($csproj in $csprojFiles) {
              $content = Get-Content $csproj.FullName
              
              # For SDK-style: Replace <TargetFramework>
              $content = $content -replace '<TargetFramework>.*</TargetFramework>', '<TargetFramework>net481</TargetFramework>'
              
              # For legacy-style: Replace or add <TargetFrameworkVersion>
              if ($content -match '<TargetFrameworkVersion>.*</TargetFrameworkVersion>') {
                $content = $content -replace '<TargetFrameworkVersion>.*</TargetFrameworkVersion>', '<TargetFrameworkVersion>v4.8.1</TargetFrameworkVersion>'
              } else {
                # Add if missing (insert after first <PropertyGroup>)
                $firstPropertyGroup = $content | Select-String -Pattern '<PropertyGroup>' | Select-Object -First 1
                if ($firstPropertyGroup) {
                  $content = $content -replace '<PropertyGroup>', '<PropertyGroup><TargetFrameworkVersion>v4.8.1</TargetFrameworkVersion>'
                }
              }
              
              Set-Content $csproj.FullName $content
            }
          }
        shell: pwsh

      # Step 6: Restore NuGet packages and build tools with MSBuild
      - name: Restore and build tools
        run: |
          $tools = @("SharpHound", "Seatbelt", "Rubeus", "Certify", "SharpSCCM")
          foreach ($tool in $tools) {
            $sln = Get-ChildItem -Path ./$tool -Recurse -Include *.sln | Select-Object -First 1
            if ($sln) {
              & ./nuget.exe restore $sln
              msbuild $sln /p:Configuration=Release /p:Platform="Any CPU"
            } else {
              $csproj = Get-ChildItem -Path ./$tool -Recurse -Include *.csproj | Select-Object -First 1
              & ./nuget.exe restore $csproj
              msbuild $csproj /p:Configuration=Release /p:Platform="Any CPU"
            }
          }
        shell: pwsh

      # Step 7: Download and setup ConfuserEx
      - name: Setup ConfuserEx
        run: |
          Invoke-WebRequest -Uri "https://github.com/mkaring/ConfuserEx/releases/download/v1.6.0/ConfuserEx-CLI.zip" -OutFile "ConfuserEx.zip"
          Expand-Archive -Path ConfuserEx.zip -DestinationPath ./ConfuserEx
        shell: pwsh

      # Step 8: Obfuscate binaries (flexible path for SDK/legacy outputs)
      - name: Obfuscate with ConfuserEx
        run: |
          $tools = @("SharpHound", "Seatbelt", "Rubeus", "Certify", "SharpSCCM")
          foreach ($tool in $tools) {
            $exe = Get-ChildItem -Path ./$tool -Recurse -Include "$tool.exe" | Where-Object { $_.FullName -like "*bin\Release*" } | Select-Object -First 1
            if ($exe) {
              $crprojPath = Join-Path .\.github\config "$tool.crproj"
              $templatePath = Join-Path .\.github\config "template.crproj"
              if (Test-Path $templatePath) {
                (Get-Content $templatePath) -replace '{{EXE_PATH}}', $exe.FullName -replace '{{OUTPUT_DIR}}', "$tool\output-obfuscated" | Set-Content $crprojPath
                & ./ConfuserEx/Confuser.CLI.exe -n $crprojPath
              } else {
                Write-Output "Template crproj not found for $tool"
              }
            } else {
              Write-Output "Executable for $tool not found in bin\Release"
            }
          }
        shell: pwsh

      # Step 9: Package and store artifacts
      - name: Package artifacts
        run: |
          $date = Get-Date -Format "yyyy-MM-dd"
          $tools = @("SharpHound", "Seatbelt", "Rubeus", "Certify", "SharpSCCM")
          foreach ($tool in $tools) {
            if (Test-Path ./$tool/output-obfuscated) {
              Compress-Archive -Path ./$tool/output-obfuscated/* -DestinationPath "./$tool-$date.zip"
            }
          }
        shell: pwsh

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: obfuscated-binaries-net481
          path: |
            *.zip
          retention-days: 7